添加方案
sgalal/awesome-rime pull request #11
Opened 2021-03-23 16:06 UTC by shinzoqchiuq

2021-03-23 16:31 UTC, laubonghaudoi approved these changes

2021-03-24 00:20 UTC, sgalal requested changes

2021-03-24 00:20 UTC, sgalal commented on README.md
> +- **34**  [andy0130tw/iridium-bpmf ](https://github.com/andy0130tw/iridium-bpmf) - 銥 \[Ir\] 注音 — \(又是一個\) 基於 RIME、參酌其它注音輸入法習慣、符合臺灣使用習慣為規準的注音輸入方案。
```suggestion
- **34** [andy0130tw/iridium-bpmf](https://github.com/andy0130tw/iridium-bpmf) - 銥 \[Ir\] 注音 — \(又是一個\) 基於 RIME、參酌其它注音輸入法習慣、符合臺灣使用習慣為規準的注音輸入方案。
```

2021-03-24 01:04 UTC, sgalal approved these changes

2021-03-24 01:04 UTC, merged